-- SQL script to mark existing migrations as run in the migrations table
-- Generated by assistant on behalf of user
-- NOTE: Review before applying. Assumes `migrations` table already exists.

INSERT INTO `migrations` (`migration`, `batch`) VALUES
('0001_01_01_000000_create_users_table', 1),
('0001_01_01_000001_create_cache_table', 1),
('0001_01_01_000002_create_jobs_table', 1),
('2025_08_01_134206_create_personal_access_tokens_table', 1),
('2025_08_01_140727_add_profile_fields_to_users_table', 1),
('2025_08_01_142553_create_mood_entries_table', 1),
('2025_08_01_143224_create_meditation_sessions_table', 1),
('2025_08_04_081339_add_google_oauth_fields_to_users_table', 1),
('2025_08_08_124704_add_role_id_to_users_table', 1),
('2025_08_08_125713_create_roles_table', 1),
('2025_08_15_000001_create_challenges_table', 1),
('2025_08_15_000002_create_challenge_user_table', 1),
('2025_08_16_010000_add_completed_and_timestamps_to_challenge_user_table', 1),
('2025_08_19_000001_create_diagnostics_table', 1),
('2025_08_19_100000_create_specialists_table', 1),
('2025_08_19_100100_create_appointments_table', 1),
('2025_08_26_120000_add_details_to_mood_entries_table', 1),
('2025_08_29_120000_create_login_otps_table', 1),
('2025_08_30_000000_create_sessions_table', 1),
('2025_09_04_000002_add_scope_to_diagnostics_table', 1),
('2025_09_04_000003_create_annual_diagnostics_table', 1),
('2025_09_04_000004_migrate_legacy_annual_diagnostics', 1),
('2025_09_30_120000_add_avatar_to_users_table', 1);
